image: node:10-slim

stages:
- build
- style
- test
- deploy

before_script:
  - npm i -g yarn
  - yarn install

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/

style:
  image: node:10-alpine
  stage: style
  script:
  - yarn style:check
  except:
  - tags

1:2 test node:
  image: node:10-alpine
  stage: test
  script:
  - yarn coverage:cover
  after_script:
  - yarn test
  except:
  - tags

2:2 test node:
  image: node:8-alpine
  stage: test
  script:
  - yarn test
  except:
  - tags

coverage:check:
  image: node:10-alpine
  stage: test
  script:
  - yarn coverage:cover
  - yarn coverage:check
  except:
  - tags

coverage:report:
  image: node:10
  stage: test
  script:
  - yarn coverage:cover
  after_script:
  - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}" -f coverage/*.json
  except:
  - tags

deploy:npm:
  stage: deploy
  image: priestine/semantics:latest
  script:
  - priestine-semantics
  - bash build.sh
  only:
  - master

deploy:docker:
  stage: deploy
  image: alpine:latest
  before_script:
  - echo ""
  script:
  - bash docker_build.sh
  only:
  - tags

pages:
  stage: deploy
  script:
  - npm run build:docs
  - mkdir .public
  - cp -r docs/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
